fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: 'adoracionperpetua.bilbao@gmail.com'
        sender_name: 'Adoración perpetua Bilbao'
    group:
        group_class:   FOS\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager