sonata_admin:
    title: 'Adoración Bilbao'
    options:
        title_mode: 'single_text'
    search: false
    show_mosaic_button:   false
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
        groups:
            Adoradores:
                on-top: true
                label: ~
                label_catalogue: ~
                icon: '<i class="fa fa-circle-o"></i>'
                item: admin.adorador

            Confesores:
                on-top: true
                label: ~
                label_catalogue: ~
                icon: '<i class="fa fa-circle-o"></i>'
                item: admin.sacerdote

            Calendarios:
                on-top: false
                label: ~
                label_catalogue: ~
                icon: '<i class="fa fa-circle-o"></i>'
            
            Peticiones del obispo:
                on-top: true
                label: ~
                label_catalogue: ~
                icon: '<i class="fa fa-circle-o"></i>'
                item:   admin.obispo

            Peticiones personales:
                on-top: true
                label: ~
                label_catalogue: ~
                icon: '<i class="fa fa-circle-o"></i>'
                item:   admin.peticion

            Acción de gracias:
                on-top: true
                label: ~
                label_catalogue: ~
                icon: '<i class="fa fa-circle-o"></i>'
                item:   admin.gracias

            Noticias:
                on-top: true
                label: ~
                label_catalogue: ~
                icon: '<i class="fa fa-circle-o"></i>'
                item:   admin.noticia


    templates:
        layout: standard_layout.html.twig
        show: 'crud/show_noticia.html.twig'

    assets:
        # stylesheet paths to add to the page in addition to the list above
        extra_stylesheets: ['bundles/app/css/admin.css','bundles/sonataadmin/vendor/admin-lte/dist/css/skins/skin-blue.min.css','bundles/app/css/fullcalendar.min.css']

        # stylesheet paths to remove from the page
        remove_stylesheets: ['bundles/sonataadmin/vendor/admin-lte/dist/css/skins/skin-black.min.css']
        
        # javascript paths to add to the page in addition to the list above
        extra_javascripts: ['bundles/app/js/fullcalendar.min.js']
sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
