twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'form/calendar.html.twig'
        - 'form/image.html.twig'
        - '@SonataCore/Form/datepicker.html.twig'
        - 'crud/base_noticia.html.twig'
